### ISSUE TITLE
Request for option to hide chart header and toolbar

### ISSUE THREAD

**Issue by ikesh-v1** [kyndryl-design-system/shidoka-charts#11]
Pretty much what the title says, we want to be able to turn off the header, either by css or typescript

**Comment by ikesh-v1** [comment]
Hi @brian-patrick-3, my use case is to show the chart without the header for a widget in Enterprise Marketplace, like the mock attached, since its it widget and we are using our own header, there isn't enough space and need for the header
<img width="753" alt="Screenshot 2024-02-23 at 7 51 29 PM" src="https://github.com/kyndryl-design-system/shidoka-charts/assets/156079496/a57d0d52-4e74-44b1-8545-2de928d59593">

**Comment by marcosebastianlopez** [comment]
Hi, if you're referring to the actual Console Widget itself, right now this is not a Shidoka component. It is being planned in the future releases for Shidoka to supply components like the Widget for the dashboard. Is this widget showing up on Console? If yes, please bring this up with the Console team: carmijor@kyndryl.com or richard.esmonde@kyndryl.com. I can tell you if you are bringing this widget over to Console though, you will not be able to do what you're asking for as I wrote those guidelines myself.

**Comment by brian-patrick-3** [comment]
This is what they want to hide, for clarification:

![Image](https://github.com/kyndryl-design-system/shidoka-charts/assets/126408222/e42556a5-b20a-42b1-89a6-98decdc7df35)
