### ISSUE TITLE
Doughnut chart peripheral value is missing

### ISSUE THREAD

**Issue by mrselvamca** [kyndryl-design-system/shidoka-charts#16]
Most of the times, doughnut chart peripheral values is missing.

<img width="453" alt="Screenshot 2024-04-08 at 10 32 30 PM" src="https://github.com/kyndryl-design-system/shidoka-charts/assets/162680174/6f8599b1-45e8-490d-a4de-fc40e69fa23f">

In above image, green color value (marked as square) is missing. But whenever we hover, then value will be shown.

<img width="453" alt="image" src="https://github.com/kyndryl-design-system/shidoka-charts/assets/162680174/db9b3cd5-0d67-4918-bb46-c055a8b417c5">

Kindly take a look on this.

**Comment by brian-patrick-3** [comment]
In this case, it probably can't show the value because the space is too limited, so working as intended. This uses the datalabels plugin, which you can experiment with if you'd like: https://chartjs-plugin-datalabels.netlify.app/
