### ISSUE TITLE
[Doughnut] Request for control over the text in the center

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-charts#7]
**Is your feature request related to a problem? Please describe.**
I need to show a different center text in a doughnut chart instead of the out of the box message shidoka gives. 

<img width="651" alt="image" src="https://github.com/kyndryl-design-system/shidoka-charts/assets/122545343/3520041f-d3e8-42ca-a2a3-e5a83b36e7e6">

**Describe the solution you'd like**
If the out of the box plugin can be made optional then center space gives me a clean slate for my plugin to write any text over there.
I am referring to this out of the box plugin for center text that shidoka uses: https://github.com/kyndryl-design-system/shidoka-charts/blob/main/src/common/plugins/doughnutLabel.js#L6

**Comment by cunningham-kyndryl** [comment]
@bikashp2023  can you explain the use case for needing to overwrite the center content?

**Comment by bikashp2023** [comment]
@cunningham-kyndryl I need to present numbers with commas to enhance readability, both in the peripheral and at the  center. I am not able to do it in the center as, for shidoka donut  charts center text is not optional for me to have a clean slate to write my own text.

As demonstrated below, the center text needs to have commas in the number.

![image](https://github.com/kyndryl-design-system/shidoka-charts/assets/122545343/b524dda5-de21-4dfe-87a2-3f9ad153896a)
