### ISSUE TITLE
Request for Geo world bubble map with enhancement 

### ISSUE THREAD

**Issue by ashishpawar12** [kyndryl-design-system/shidoka-charts#9]
**Is your feature request related to a problem? Please describe.**
We need Geo map with below functionality

1) Need a zoom in/out with focus on some region
2) onclick on region point map should be drill down with more point on same region with some location zooming
Please refer to below screen record for more understanding

Screen Recording 2024-01-12 at 10.07.05 AM.mov…

**Comment by ashishpawar12** [comment]
https://github.com/kyndryl-design-system/shidoka-charts/assets/18259137/d8fe3df5-6dd9-4d44-9079-89ded2b53e44

**Comment by brian-patrick-3** [comment]
The third party chartjs geo plugin is not supported by the third party chartjs zoom plugin, so this feature is not possible. 

Two options:

1. You can hook into click events on the chartjs instance to render a new chart based on the clicked region.
2. You need to use an alternate solution with full mapping capabilities such as Google Maps or similar.
